database:
  url: postgres://casper:casper@localhost:55432/casper?sslmode=disable

states:
  - type: local
    paths:
      - fixtures/terraform.tfstate

iac:
  paths:
    - "modules/**/*.tf"
    - "envs/**/*.tf"
  module_dirs:
    - modules/
