database:
  url: postgres://casper:casper@localhost:55432/casper?sslmode=disable

states:
  - type: local
    paths:
      - fixtures/terraform.tfstate

iac:
  paths:
    - /Users/lowkeydev/code/infrastructure/**/*.tf
    - /Users/lowkeydev/code/terraform-aws-vpc/**/*.tf
  module_dirs:
    - /Users/lowkeydev/code/infrastructure/modules
    - /Users/lowkeydev/code/infrastructure/services
    - /Users/lowkeydev/code/terraform-aws-vpc/modules
